######################################################################
# Automatically generated by qmake (3.1) Mon Mar 5 15:59:50 2018
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
